// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6b7e30fe-e424-4214-ac85-b7f9ac03bef4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GPMl3xrRh",
    "aws_user_pools_web_client_id": "5niaiseobn3cpibett1qtutv73",
    "oauth": {},
    "aws_user_files_s3_bucket": "sexual-abuse-files-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
